### ISSUE TITLE
Loss and some slice of the output tensors become NAN

### ISSUE THREAD

**Issue by krenusz** [ML4ITS/mtad-gat-pytorch#19]
When you rerun the train.py after a while the use_bias parameter causing NANs in the outputs of the Attention layers. The situation occures after the Bias is added to the tensor. Do you have any explaination or solution beside to set the use_bias parameter to False?

**Comment by srigas** [comment]
Kind of late to the party, but this is most likely due to the initialization of the biases, as has been pointed out by [fga-telenor](https://github.com/fga-telenor) in [this](https://github.com/ML4ITS/mtad-gat-pytorch/issues/13) issue. Try adding the line `nn.init.zeros_(self.bias.data)` two times in the `modules.py` file: one for each time the biases are initialized.
