### ISSUE TITLE
tqdm is not imported in prediction.py + request

### ISSUE THREAD

**Issue by TKrom** [ML4ITS/mtad-gat-pytorch#7]
Dear authors,

First of all, I would like to thank you for publicly offering your implementation version of this method from Zhao et. al (2020) on Github. This material greatly helps me in conducting my master thesis research into unsupervised methods for multivariate time series anomaly detection.

I have one problem I have run into, an error while executing your code for the SMAP dataset. training goes well up until predicting and calculating the anomaly scores from line 167 in train.py onwards. Here the predict_anomalies function on line 118 calls the get_score function from prediction.py, which on line 51 returns "NameError: name 'tqdm' is not defined". This is probably due to the lack of the tqdm import statement at the beginning of the prediction.py file.

I hope this feedback is of value to you.

Apart from mentioning this problem, I have another question. Is it possible to load different datasets into your implementation, or is it hard to do this due to hardcoding practices for example? My intention is to load a custom multivariate time series dataset and evaluate the performance of this method. The dataset comprises several .csv files, each having data of one of multiple IoT sensors where columns constitute the multivariate features and rows the time dimension. In order to transform this data to your data format requirements, I will condense these files into one big file where the multivariate sensor features of all sensors are combined in the columns. Could you recommend a way to load this file into your implementation? I was thinking of adapting the preprocess.py file to do so. Perhaps you could add the option to load custom datasets in the future.

In any case, thank you very much for your efforts.

**Comment by axeloh** [comment]
Hi, thanks for your input.

Regarding the import error, I am not sure how this came to be. Perhaps the import line was deleted during cleanup of the code. Anyway, tanks for lettis us know. Tqdm provides a loading bar, and can be installed using pip, and imported with `from tqdm import tqdm`

The answer to your second question is yes, it should be quite straight forward to use a custom dataset. However, there are some things you must do. As you say, I suggest you make your own method in `preprocess.py`, which is loading your data. This method should be called instead of the `get_data()` method in `train.py`: 
https://github.com/ML4ITS/mtad-gat-pytorch/blob/c7bb82371ad8980e1e2b3f45867a1c5c78f85f59/train.py#L36-L41
Just add another elif-statement with the name of your dataset, and make sure to call `train.py` using `--dataset name-of-your-dataset`

Your method should return a training set (x_train) and a test set (x_test), where the testing set also could have corresponding test labels (y_test). x_train/x_test should be a numpy array of shape (n, k), where n is the number of rows, and k is the number of columns. y_test should be a numpy array of length n, with values 0 or 1, where 0 means no anomaly, and 1 means anomaly. If you don't have labels for the test set, you just set y_test to None, and the model will do prediction but not evaluate the model against a ground truth. 

You must also provide a line in `get_target_dims()` in `utils.py`, where you specify which column you want to model, or None if you want to model every column. 
Also, in `train.py` you should add your dataset in the dictionaries at line 126 and 141. 

Hope this helps, and good luck with your master thesis!

**Comment by TKrom** [comment]
Hi Axel,

Thank you very much for your help, this really helps me conduct my master thesis!

Your suggested steps worked like a charm.

When evaluating the the model on my custom multivariate dataset (which unfortunately lacks ground truth labels) visually, in general I was very pleased with the results. I noticed however that some features were really closely fit, while other features were quite badly fit by the model. I am trying to understand why this could be. I presume it has something to do with the patterns being longer than the sliding window size. Attached are two examples, one feature that was fit really well, and one that was not fit well. The window size used is 100, and in the good case comprised multiple patterns, and in the bad case comprised less than pattern sized sections. What potential remedy step would you suggest? Increasing the window size, or perhaps another hyperparameter? I would be happy to hear your input!

Secondly I was wondering why you made the choice to use a GRU-based decoder instead of a VAE as the reconstruction model? Is there a chance that you would add an option to select a VAE in your implementation in the near future? I am trying to stay as close as possible to the original model of Zhao et. all (2020) for evaluation purposes. I would be very grateful if you would decide to incorporate this option.

In any case, thank you for providing this solution as is, you did an awesome job!

Kind regards,

Teun

![Bad fit](https://user-images.githubusercontent.com/90958058/134142830-657247d3-e6fe-40ee-9e76-aaec64cc4ff4.jpeg)
![Good fit](https://user-images.githubusercontent.com/90958058/134142835-37b5b772-fef3-48b7-a59e-7cdef2f37c82.jpeg)

**Comment by axeloh** [comment]
Hi again, I am glad to hear that my reply was helpful to you! 

From what I can see, there is not too much pattern present in the first plot. In case of lacking pattern, the model might just output values near the average value, as it sees no way of improving. In general, you could play around with different hyperparameters, and check if the overall performance increases (window size, embedding dimension, number of layers, and size of GRU layer, FC layer, and Recon layer, etc).

However, seeing as the second plot shows that the model is capable of modeling patterns very accurately, you might not want to change too much. In my opinion, the most important thing is that the model is performing well for features that express clearer temporal patterns. In my experience, real-world data will often have certain features that are hard/impossible to predict, and for those, the best thing might just be to predict an average value (you could also remove them from the target features that are being predicted). 

For your second question, I talk about this in #2. Actually, by talking with authors and others, the VAE seems to be somewhat unstable and hard to train, which was one of the reasons why we chose a simpler reconstruction model. We are not really working on this project anymore, so we do not plan to extend it to include the VAE. Maybe you will be the one to take up the challenge? ;-)

Best regards,
Axel

**Comment by Avv22** [comment]
Hello Dear @axeloh 

I tried to run the model on my custom dataset that has 17 features. For anomaly purposes for reconstruction exactly, what I should change please given I build custom dataset loader?

**Comment by Avv22** [comment]
@axeloh I tried running on my custom data and followed your changes above. I tested the model on new unseen data but it failed even though I have 0.33 reconstruction loss on the test data during training. Any suggestion please? Also, how to get those figures below as my dataset has 17 features and no anomaly label there. So I set y_test to None as you said. Any help please? 

Second question: why you need to visualize and plot training anomalies, etc. please? 

![image](https://github.com/user-attachments/assets/e282a3a0-51d1-467b-b5b9-ef74947048e4)

Also, I noticed that the model suffer to model near linear feature that has nearly linear line across time access. Do you recommend to drop such features please? 
![image](https://github.com/user-attachments/assets/5b947d27-dc9c-4f4e-8522-67dccef4dd12)

![image](https://github.com/user-attachments/assets/fbc2b122-353d-4cfc-b81e-fa97f28eb0ad)

![image](https://github.com/user-attachments/assets/ae6684ff-66e5-4dcc-9e7c-a66a3c36fc19)

![image](https://github.com/user-attachments/assets/08c995cf-075f-4937-9744-86147a5161a5)
